version: '1.0.0'

services:
   backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - DBURL=${DBURL}
   
   frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5000:3000